### ISSUE TITLE
Close button CSS

### ISSUE THREAD

**Issue by vaidik** [voronianski/jquery.avgrund.js#20]
Shouldn't this code snippet be in `avgrund.css`?

``` css
.avgrund-close {
    display: block;
    text-transform: uppercase;
    color: #555;
    text-decoration: none;
    position: absolute;
    top: 6px;
    right: 10px;
    font-size: 13px;
}
```

Its included in styles.css. In most of the cases, perhaps we would not want to include styles.css which is the CSS file for the demo on your Github pages.
